using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ZonSäckGenerator
{
    class Arrays
    {
        string[] LowArray = new string[] { "Spade",
            "Fin Sten",
            "Tokjosflaska(250ml)",
            "Två tomma glasflaskor",
            "Förra månadens utgåva av Zonkuriren",
            "Tvättsvamp",
            "Ett gäng spik och skruvar",
            "Soffkudde",
            "Sandpapper",
            "En påse ätbara minitiatyrträd",
            "Klädhängare",
            "Nyckelknippa till okända lås",
            "Varm filt",
            "Målarpenslar",
            "300 tandpetare",
            "Kortlek",
            "Stenkulor 25 stycken 2",
            "Läderfotboll",
            "Metspö i bambu med metkrok",
            "Ankare i gjutjärn",
            "Fyra fina björkkåsor",
            "Två flaskor fulmäsk",
            "Vanliga knegarkläder",
            "Slagruta",
            "Glasögon",
            "Flaska terpentin 1L",
            "Liggunderlag & sovsäck",
            "Campingstol",
            "Fickspegel",
            "Djungelolja",
            "Munspel",
            "Regnrock med sydväst",
            "Ett par torra stövlar",
            "Krokvåg, max 200kg",
            "Nutida läderpansar för 1t3 områden",
            "Varm lädermössa m. öronlappar",
            "Strykjärn",
            "Trofé: ett uppstoppat fågelhuvud",
            "Fältkök, fotogen",
            "Sexfots trästav",
            "Skinnrock m. gömda fickor",
            "Vinterrockar 1t3 st",
            "En snitsig spatserkäpp",
            "Fyrmannatält",
            "Bordsur",
            "Lösnäsa m. mustasch",
            "Smörjolja",
            "Skokräm",
            "Cykelkedja",
            "5 torra par sockar",
            "Flugsmälla",
            "En burk med konstiga svampar",
            "Knasapulverspanna m. 3 stålkoppar",
            "Stekpanna i gjutjärn 27cm",
            "Skyddshandskar i läder",
            "Slangbella",
            "Slängkappa",
            "Säck med cement",
            "Säck med grus",
            "Presenning 4x2m",
            "Tom forntida plåtlåda 'Åbåj'",
            "Enkla plåster och bandage",
            "Sylåda",
            "4 kg potatis",
            "Bucklig forntidsfälg",
            "Bultsax",
            "Bågfil",
            "Metallkratta",
            "Fågelbur",
            "Borrsväng",
            "Handsåg",
            "Handyxa",
            "30m brunsnöre"
            }; //Prylar med låg användbarhet eller lågt penningvärde
        string[] MedArray = new string[] { "Medicinväska",
            "En veckas ransoner",
            "Kvicksilvertermometer",
            "Låsdyrksset",
            "25 meter rep",
            "Skruvklampar, 3 st",
            "Forntida STOP-skylt",
            "5kg kraftapärer",
            "Biljardkö",
            "Ett pund snus",
            "Kofot",
            "Bok - 'Den lustfyllda reptilhushållerskan'",
            "Stålhink",
            "Läderbunden anteckningsbok med skrivdon",
            "Stilfull tå-ring",
            "Ståltråd 3 meter",
            "Sprayfärg",
            "Nödproviant i stasis för 2 dagar",
            "En marmorstatyett föreställande en fågel",
            "Finurligt, ihopfällbart metspö i trä med metkrok",
            "Liten fotpump",
            "Solglasögon",
            "Skyddsglasögon",
            "Kompass",
            "Hockeyarmskydd",
            "Krutstubin 10m",
            "Kobåjsarhatt i läder",
            "Vatten i stasis 2 liter",
            "Paket med tuschpennor i 10 färger",
            "Borrar till trä, 5 - 50 mm",
            "Trofé: ett uppstoppat varghuvud",
            "Ljuddämpare för moderna vapen - Nårrlands Guld 50cl",
            "Verktygsset",
            "Åttamannatält med förmak",
            "Ihopfällbar stege, 1.8 m",
            "Kängurustylta",
            "Oöppnad burk med knasapulver",
            "Rulle med 27st forntida plastkassar'KOOPERATIVET'",
            "Ansiktsfärg för kamouflage",
            "Förstärkta skyddshandskar",
            "Gift, skadande 1t4 doser",
            "12 golfbollar",
            "Mystisk stålskiva 'Canal Digital'",
            "Gipstomte",
            "En burk lim",
            "Handvärmare, 1t10",
            "Smink i glada färger",
            "Orientalisk matta",
            "Röd underställspyjamas m. evakueringshål",
            "Bok - 'Hundra sätt att flå en rubbit'",
            "20m flugpapper",
            "Lödpenna m. tennstavar",
            "40m björntråd",
            "Ormskinnsgaloscher",
            "Hatt med tjusig domherrefjäder",
            "Gammalt mopedstyre med knappar och grep"
            }; //Prylar med medelhög användbarhet eller medelhögt penningvärde
        string[] HighArray = new string[] { "Ett fåtal ädelstenar",
            "20 skarprättarpatroner",
            "12 stycken patroner kaliber .45",
            "Signalbloss 1t10 st",
            "1 tub lugnande piller, 12 st",
            "Gasmask",
            "Bok - 'Zonterapi med Dr Löfenwråål'",
            "Bok - 'Molijoxer, mojänger och hur man fixar dem'",
            "Bok - 'Underliga berättelser från Österhavet - Begränsad utgåva'",
            "Illasmakande forntidspasta 'Alcogel'",
            "Karta över den kända världen",
            "Nutida handgranat",
            "Hockeybenskydd",
            "Hockeyhjälm",
            "Rubbitsaxar 1t3 stycken",
            "Vattenrenande tabletter 20x1L",
            "Pentylstubin 20m",
            "Nutida medeltungt pansar för 1t3 områden",
            "Cykelhjälm",
            "Hård plasthjälm med visir",
            "Borrar till metall, 3 - 14mm",
            "Multifunktionell armékniv",
            "Trofé: ett uppstoppat rubbithuvud",
            "Rökgranater 1t3 st",
            "Läkedrog I, 1t6 st",
            "Läkedrog II, 1t3 st",
            "Knivsäker väst",
            "Skyddsoverall",
            "Handstrålkastare utan kraftpaket",
            "12mannatält med förmak och rökrum",
            "Dynamitspjut 1t6 st",
            "Armbandsur m. miniräknare",
            "Motoriserad knivslip med kraftpaket",
            "'Senilkärra', ihopfällbar",
            "Forntida vajerlås m. nyckel",
            "Forntida skyddshandskar, giftsäkra",
            "Reservdelar till automat",
            "Motgift, 1t4 doser",
            "Chockgranater, 1t4",
            "Dynamitfälla",
            "Skarpskyttesikte",
            "Självuppblåsande gummibåt, 2pers",
            "Riktigt många dynamitgubbar",
            "Läkande strimlor med fina motiv 'Bamse'",
            "Solglasögon 'Aviatör'",
            "Gift, dödande 1t4 doser",
            "Illgula rullskor",
            "Vattenpistol i genomskinlig plast",
            "Ekoxehorn",
            "En rulle isoleringstejp",
            "Varmhållningsflaska med värmepaket",
            "Kemiska engångslysstavar, 1t12",
            "Kraftkablar med krokodilmun",
            "Insatsslägga 'Dörrknack'",
            "Duschdraperi med motiv 'Dörty Harry'"
            }; //Prylar med hög användbarhet eller högt penningvärde
        string[] FireArmArray = new string[] {
            "Dubbelpipig hagelbrakare",
            "Enkelpipigt pumphagel",
            "Avsågad hagelbrakare",
            "Hagelpistol",
            "Skarprättarpistol",
            "Skarprättargevär",
            "Optiskt riktmedel, 2x förstoring",
            "Dioptersikte",
            "Bajonett m. gevärsmontering",
            "5 Skarprättarpatroner",
            "10 Skarprättarpatroner",
            "6 patroner .45",
            "12 patroner .45",
            "10 patroner 15mm",
            "4 hagelskott",
            "8 hagelskott",
            "Musköt",
            "Derringer .45S",
            "Armborstpistol",
            "Tryckluftsharpun",
            "Slaglåspistol 15mm",
            "Engångspistol flechette",
            "Compoundbåge"
        }; //Vanliga skjutvapen
        string[] LowTechWeaponArray = new string[] {
            "Knogjärn",
            "Machete",
            "Stor böjd enhandskniv 'Kukri'",
            "Ett schysst järnrör",
            "Nutida tungt bröstpansar",
            "Stålkask",
            "Golfklubba (järnsexa)",
            "Kricketracket",
            "Vässad hockeyklubba",
            "Slägga",
            "Lång kniv",
            "Sabel",
            "Fyrkantigt huggsvärd",
            "Lättmetallstav, 4 fot",
            "Ishacka",
            "Tvåhandssvärd",
            "Liten vägskyltssköld",
            "Stor vägskyltssköld",
            "Lättgömd stickkniv",
            "Fälgkors",
            "Hemmagjord dänghammare",
            "Spjut",
            "Ihopknuten vävsäck med vasst skrot i",
            "Pilbåge",
            "Pianotråd med handtag",
            "Redig klubba",
            "Stridsyxa"
        }; //Vanliga närstridsvapen
        string[] RareItemArray = new string[] {
            "Kassavalv 'Electrolux'",
            "Rödpunktssikte",
            "Forntida Lyshjälm",
            "Underliga cylindrar AAA",
            "1 fat bensin i stasis, 1T100+(1T4×25) liter ",
            "Forntida Nationsflagga",
            "Forntida fäktningshjälm m. vit heltäckande skyddspyjamas",
            "Sovjetisk förbrytare i stasis",
            "Automatisk fotvårdare m. kraftpaket",
            "Borrmaskin med A-paket samt 6mm metall-borr",
            "Forntida tatueringspenna m. färgpaket",
            "Forntidspuffra 9mm m. 20 patroner",
            "Batteriladdare (drivs av solenergi).",
            "Röd tub 'Brandsläckare'",
            "Julgran i plast (ihopfällbar)",
            "Forntidsljuddämpare",
            "Blandade fornkryddor i stasis - 'Hot 'n Spicy'",
            "Forntidsrevolver .38",
            "Forntidspicka 9mm",
            "Röjsåg m. halv tank",
            "Forntidskarbin",
            "Rödblå spindeldräkt för barn",
            "Plexiglassköld, stor",
            "Stickpenna 'Epinefrin', 1t4 st",
            "Ljusförstärkande solglasögon",
            "Forntida enkelöga med nattsyn",
            "Läkedrog III,  1t3 st",
            "Forntidsklenod i stasis - 'ZWEIHÄNDER'",
            "Böjd utlandsklinga 'BSHIDO'",
            "Bordsfläkt m. kraftpaket",
            "Högteknologisk protes, 1t4 för extremitet",
            "Bok - 'Robotik och Automation - Illustrerad'",
            "Sprängskiss av forntidsbössa",
            "Forntida multiverktyg",
            "Gummitandat snömonster 'Sno-Tric'",
            "Vibrokniv RAMBO IV",
            "Forntida överlevnadsdräkt",
            "Knasterbatong m. kraftpaket",
            "Glasfiberpilbåge",
            "Lasersvets",
            "Plattskärm m. kraftpaket, visar vy av blågrönt klot i rymden",
            "Glascylinder m. lysande grön vätska",
            "Läkedrog II 1t4 doser",
            "Forntida matpulver - 'MUTANT MASS' 8kg",
            "Kravallhjälm 'POLIS'",
            "Skottsäker forntidsväst",
            "Gasoltub i stasis",
            "Gräsklippare",
            "Dykardräkt m. lufttuber 'Nautilus'",
            "Fungerande cykel 'Döden Bakom Styret'",
            "Snitsig kostym i självlysande tyg",
            "En låda forntidsgranater",
            "Granatgevär 'C-G'",
            "Motorsåg 'Husqvarna'"
        }; //Extraordinära fynd
        string[] FyndFlavorsArray = new string[] {
        "Gömman finns djupt nere i en gammalt kommunhus, i en underlig bunker där RP efter dörren forcerats finner mängder med konstiga prylar strödd bland skelett och sönderrostad gym-utrustning.",
        "Vid närmare inspektion av en gigantisk hög av oanvändbart skrot kan man hitta vindlande gångar förstärkta med strategiskt placerade stålbalkar. Efter att ha desarmerat fällorna kan RP hitta en veritabel hord av fornskrot, omisstagligen insamlat av en erfaren zonfarare som dog innan denne hann dra nytta av allt fantastiskt byte.",
        "Bakom några tydligt ditspikade plankor på baksidan av ett zonrövar-utedass ramlar det ut en hög av eftertraktade zongrunkor."
        };
        string[] FyndLabelFlavorsArray = new string[]
{
                    "Zonfynd bekräftat!",
                    "Skattgömma uppgrävd!",
                    "Grunkor överkomna!",
                    "Rikedom uppnådd!",
                    "Molijoxer avjordade!",
                    "Antikviteter värdesbedömda!",
                    "Fornskatter upphittade!",
                    "Värde kalkylerat!",
                    "Prylhög ihopslängd!",
                    "Värdesaker bortgömda!",
                    "Ovärderligheter ihopskrapade!"
};
        int[] findingArray = { 5, 15, 45, 70, 75, 85 };
        public string[] LowValArray => LowArray;
        public string[] MedValArray => MedArray;
        public string[] HighValArray => HighArray;
        public string[] FireArmsArray => FireArmArray;
        public string[] LowTechWeaponsArray => LowTechWeaponArray;
        public string[] RareItemsArray => RareItemArray;
        public string[] FyndFlavorArray => FyndFlavorsArray;
        public string[] FyndLabelFlavorArray => FyndLabelFlavorsArray;
        public int[] findArray => findingArray;
    }
}
